### PR TITLE
planner and device code: fixing merge issues

### PR DESCRIPTION
**Pull request by baywet**

### CODE REVIEW

**Comment by baywet** [comment]
@BrianTJackett we made a mistake making change in the template folder and commiting and then merging on this one. I had to collect the changes and commit them manually.
Now for the reog branch, I can submit a revert PR but this is going to be ugly.
You should probably branch reog into reog-clean on commit 00dc5f4f58294eede3b21f514cc670d1f16aca40.
Then cherry pick 6a517cd8fff817c471ec269f63bea29c5306be1c
Then I'll re-target this PR to the reorg clean and we should be in a good shape.
Let me know what you think

**Comment by BrianTJackett** [comment]
Agreed, should've split out the folders earlier.  I'm not as familiar with the process you are describing.  Would you be able to work with @gavinbarron to get this accomplished?

My initial thought was to take the reorg branch that we currently have (flaws and all), create new branch and separate out from the Planner code on it, then add the device code as a separate subfolder.  Will defer to you guys who have more experience in this space though.

**Comment by baywet** [comment]
I technically could "create that branch" on my repo, and then you'd only have to pull that branch from my remote, unset the upstream and push it to this remote. I don't know if this sounds easier to you?
I could also do it myself if I had contrib permissions on this repo (even temporary).
If you take the current branch, you'll have all the commit history, and the mess is going to repeat for any subsequent merge (depends on what you merge in what but you get the idea), in my experience it's always better to start of a clean commit history (hence my "cleaning procedure")

**Comment by BrianTJackett** [comment]
Granted you contrib access.  Let me know if need anything else at the moment.

**Comment by baywet** [comment]
Thanks @BrianTJackett !
There you go, you now have a feature/reorganize-codebase-clean branch and this PR is targeted to that new branch instead. You can remove my contrib permissions and merge this PR.

**Comment by BrianTJackett** [comment]
Are we ok to remove the older branches for feature/reorganize-code-base and feature/day-template?  Based on what I'm hearing those appear to be included in this new clean branch, correct?

**Comment by baywet** [comment]
the old reorg yes, the day template no. I didn't bring these commits https://github.com/microsoftgraph/dotnetcore-console-sample/commit/d0ae53f1d7c51737a42ee7a2c6d0bcf45040b8ef and https://github.com/microsoftgraph/dotnetcore-console-sample/commit/0d3a50fe581f0339f0b8a79d0bdd5637d5310f4a
because they were a result of my "bad merge" on the original PR for Planner.
I'm going to create a PR for that.
The rest is here, with different commit sha as I either did manual copies for my stuff or cherry picking.

**Pull request merged**
